# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: "Clean custom"
description: "Custom clean step to run after PR is closed"
# this inputs are always provided by flowzone, so they must always be defined on the composite action
inputs:
  json:
    description: "JSON stringified object containing all the inputs from the calling workflow"
    required: true
  secrets:
    description: "JSON stringified object containing all the secrets from the calling workflow"
    required: true
runs:
  using: "composite"
  steps:
    # since core versioning operates only at root level
    - name: Version package.json
      shell: bash
      run: |
        tmppkg="$(mktemp)"

        version="$(jq -r '.version' ../package.json)"

        jq --arg version "${version}" '.version=$version' package.json > "${tmppkg}"

        cat < "${tmppkg}" | jq -r > package.json

        rm -f "${tmppkg}"
