# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: "Publish custom"
description: "Custom publish step to run after all tests have passed"
# this inputs are always provided by flowzone, so they must always be defined on the composite action
inputs:
  json:
    description: "JSON stringified object containing all the inputs from the calling workflow"
    required: true
  secrets:
    description: "JSON stringified object containing all the secrets from the calling workflow"
    required: true
runs:
  using: "composite"
  steps:
    - name: Dump context
      shell: bash
      env:
        INPUTS: ${{ inputs.json }}
        SECRETS: ${{ inputs.secrets }}
        GITHUB: ${{ toJSON(github) }}
      run: |
        echo "${INPUTS}"
        echo "${SECRETS}"
        echo "${GITHUB}"

    # Test publishing release artifacts to github
    - name: Upload generated flowzone.yml
      uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3
      with:
        name: gh-release-${{ github.event.pull_request.head.sha || github.event.head_commit.id }}
        path: .github/workflows/flowzone.yml
        retention-days: 1
