# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: "Always custom"
description: "Custom step to run always"
# this inputs are always provided by flowzone, so they must always be defined on the composite action
inputs:
  json:
    description: "JSON stringified object containing all the inputs from the calling workflow"
    required: true
  secrets:
    description: "JSON stringified object containing all the secrets from the calling workflow"
    required: true
  needs:
    description: "JSON stringified object containing all the needs from the calling workflow"
    required: false
runs:
  using: "composite"
  steps:
    - name: Dump context
      shell: bash
      env:
        INPUTS: ${{ inputs.json }}
        SECRETS: ${{ inputs.secrets }}
        NEEDS: ${{ inputs.needs }}
        GITHUB: ${{ toJSON(github) }}
      run: |
        echo "${INPUTS}"
        echo "${SECRETS}"
        echo "${NEEDS}"
        echo "${GITHUB}"
